export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',

  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  LEVEL_ACCESS_DENIED: 'LEVEL_ACCESS_DENIED',

  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',
  LESSON_NOT_AVAILABLE: 'LESSON_NOT_AVAILABLE',

  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',

  INVALID_FILE: 'INVALID_FILE',
  IMPORT_FAILED: 'IMPORT_FAILED',

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  CONFLICT: 'CONFLICT',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  [ERROR_CODES.AUTH_REQUIRED]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.TOKEN_INVALID]: 401,
  [ERROR_CODES.INVALID_CREDENTIALS]: 401,

  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.ACCOUNT_SUSPENDED]: 403,
  [ERROR_CODES.SUBSCRIPTION_REQUIRED]: 403,
  [ERROR_CODES.SUBSCRIPTION_EXPIRED]: 403,
  [ERROR_CODES.LEVEL_ACCESS_DENIED]: 403,
  [ERROR_CODES.LESSON_NOT_AVAILABLE]: 403,

  [ERROR_CODES.ACCOUNT_NOT_FOUND]: 404,
  [ERROR_CODES.LESSON_NOT_FOUND]: 404,
  [ERROR_CODES.PAYMENT_NOT_FOUND]: 404,
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 404,

  [ERROR_CODES.CONFLICT]: 409,
  [ERROR_CODES.VALIDATION_ERROR]: 422,
  [ERROR_CODES.INVALID_FILE]: 422,
  [ERROR_CODES.RATE_LIMITED]: 429,

  [ERROR_CODES.PAYMENT_FAILED]: 400,
  [ERROR_CODES.PAYMENT_PENDING]: 400,
  [ERROR_CODES.IMPORT_FAILED]: 500,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
};
